
services:
  web:
    build: .
    command: sh -c "gunicorn coder_movie_bot.wsgi:application --bind 0.0.0.0:8000 & python bot.py"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: coderdatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Otabek2007
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
